/**
 * Export Service
 *
 * Generates CSV, JSON, and Markdown report strings from journal entries.
 * All CSV cells are sanitized via csvSafety.ts for formula injection prevention.
 * CSV output includes a UTF-8 BOM prefix for Excel Windows compatibility.
 *
 * This service is stateless — it generates export strings and returns them.
 * File creation is handled by the calling component (ExportButton).
 */

import type { JournalEntry, FrontmatterField, DateRange } from '../types';
import { sanitizeCsvCell } from '../utils/csvSafety';

/**
 * Generate CSV string from entries and fields.
 * Columns: date, day_of_week, word_count, quality_score, [each detected field], tags
 *
 * @param entries - Journal entries to export
 * @param fields - Detected frontmatter fields
 * @returns CSV string with UTF-8 BOM prefix
 */
export function generateCSV(
    entries: JournalEntry[],
    fields: FrontmatterField[]
): string {
    // Fixed columns
    const fixedHeaders = ['date', 'day_of_week', 'word_count', 'quality_score'];
    // Dynamic field columns
    const fieldHeaders = fields.map(f => f.key);
    // Tags column
    const allHeaders = [...fixedHeaders, ...fieldHeaders, 'tags'];

    // Header row
    const headerRow = allHeaders.map(h => sanitizeCsvCell(h)).join(',');

    // Data rows
    const dataRows = entries
        .sort((a, b) => a.date.getTime() - b.date.getTime())
        .map(entry => {
            const cells: string[] = [];

            // Fixed columns
            cells.push(sanitizeCsvCell(formatDateForExport(entry.date)));
            cells.push(sanitizeCsvCell(entry.dayOfWeek));
            cells.push(sanitizeCsvCell(entry.wordCount));
            cells.push(sanitizeCsvCell(entry.qualityScore));

            // Dynamic field columns
            for (const field of fields) {
                const value = entry.frontmatter[field.key];
                cells.push(sanitizeCsvCell(value));
            }

            // Tags — extract from frontmatter 'tags' field
            const tags = entry.frontmatter['tags'];
            cells.push(sanitizeCsvCell(tags));

            return cells.join(',');
        });

    // UTF-8 BOM prefix for Excel Windows compatibility
    return '\uFEFF' + headerRow + '\n' + dataRows.join('\n');
}

/**
 * Generate JSON export from entries.
 * Same structure as CSV but as a JSON array of objects.
 *
 * @param entries - Journal entries to export
 * @param fields - Detected frontmatter fields
 * @returns Formatted JSON string
 */
export function generateJSON(
    entries: JournalEntry[],
    fields: FrontmatterField[]
): string {
    const data = entries
        .sort((a, b) => a.date.getTime() - b.date.getTime())
        .map(entry => {
            const obj: Record<string, unknown> = {
                date: formatDateForExport(entry.date),
                day_of_week: entry.dayOfWeek,
                word_count: entry.wordCount,
                quality_score: entry.qualityScore,
            };

            for (const field of fields) {
                obj[field.key] = entry.frontmatter[field.key] ?? null;
            }

            obj.tags = entry.frontmatter['tags'] ?? [];

            return obj;
        });

    return JSON.stringify(data, null, 2);
}

/**
 * Generate a markdown report for a date range.
 * Includes: period header, averages table, highlights (best/worst day),
 * tag summary, completion rates, writing volume stats.
 *
 * @param entries - Journal entries within the date range
 * @param fields - Detected frontmatter fields
 * @param dateRange - The date range covered by the report
 * @returns Markdown report string
 */
export function generateMarkdownReport(
    entries: JournalEntry[],
    fields: FrontmatterField[],
    dateRange: DateRange
): string {
    const sorted = [...entries].sort((a, b) => a.date.getTime() - b.date.getTime());
    const lines: string[] = [];

    // Period header
    const startStr = formatDateForExport(dateRange.start);
    const endStr = formatDateForExport(dateRange.end);
    lines.push(`# Journal Report: ${startStr} to ${endStr}`);
    lines.push('');
    lines.push(`*Generated by Hindsight Journal — ${sorted.length} entries*`);
    lines.push('');

    // Averages for numeric fields
    const numericFields = fields.filter(f => f.type === 'number' || f.type === 'numeric-text');
    if (numericFields.length > 0) {
        lines.push('## Averages');
        lines.push('');
        lines.push('| Field | Average | Min | Max |');
        lines.push('|-------|---------|-----|-----|');

        for (const field of numericFields) {
            const values = sorted
                .map(e => e.frontmatter[field.key])
                .filter((v): v is number => typeof v === 'number');
            if (values.length > 0) {
                const avg = values.reduce((a, b) => a + b, 0) / values.length;
                const min = Math.min(...values);
                const max = Math.max(...values);
                lines.push(`| ${field.key} | ${avg.toFixed(1)} | ${min} | ${max} |`);
            }
        }
        lines.push('');
    }

    // Completion rates for boolean fields
    const boolFields = fields.filter(f => f.type === 'boolean');
    if (boolFields.length > 0) {
        lines.push('## Completion rates');
        lines.push('');
        for (const field of boolFields) {
            const values = sorted.map(e => e.frontmatter[field.key]);
            const trueCount = values.filter(v => v === true || v === 'true').length;
            const total = values.filter(v => v !== undefined && v !== null).length;
            const rate = total > 0 ? ((trueCount / total) * 100).toFixed(0) : '0';
            lines.push(`- **${field.key}:** ${trueCount}/${total} (${rate}%)`);
        }
        lines.push('');
    }

    // Best and worst day
    if (sorted.length > 0) {
        const moodField = numericFields.find(f => f.key === 'mood') ?? numericFields[0];
        if (moodField) {
            const withMood = sorted.filter(e => typeof e.frontmatter[moodField.key] === 'number');
            if (withMood.length > 0) {
                const best = withMood.reduce((a, b) =>
                    (a.frontmatter[moodField.key] as number) > (b.frontmatter[moodField.key] as number) ? a : b
                );
                const worst = withMood.reduce((a, b) =>
                    (a.frontmatter[moodField.key] as number) < (b.frontmatter[moodField.key] as number) ? a : b
                );

                lines.push('## Highlights');
                lines.push('');
                lines.push(`- **Best day** (${moodField.key}: ${best.frontmatter[moodField.key]}): ${formatDateForExport(best.date)}`);
                if (best.firstSectionExcerpt) {
                    lines.push(`  > ${best.firstSectionExcerpt.substring(0, 100)}...`);
                }
                lines.push(`- **Worst day** (${moodField.key}: ${worst.frontmatter[moodField.key]}): ${formatDateForExport(worst.date)}`);
                if (worst.firstSectionExcerpt) {
                    lines.push(`  > ${worst.firstSectionExcerpt.substring(0, 100)}...`);
                }
                lines.push('');
            }
        }
    }

    // Tag summary
    const tagMap = new Map<string, number>();
    for (const entry of sorted) {
        const tags = entry.frontmatter['tags'];
        if (Array.isArray(tags)) {
            for (const tag of tags) {
                if (typeof tag === 'string') {
                    tagMap.set(tag, (tagMap.get(tag) ?? 0) + 1);
                }
            }
        }
    }
    if (tagMap.size > 0) {
        lines.push('## Tags');
        lines.push('');
        const sortedTags = Array.from(tagMap.entries()).sort((a, b) => b[1] - a[1]);
        for (const [tag, count] of sortedTags.slice(0, 20)) {
            lines.push(`- **${tag}:** ${count}`);
        }
        lines.push('');
    }

    // Writing volume
    lines.push('## Writing volume');
    lines.push('');
    const totalWords = sorted.reduce((acc, e) => acc + e.wordCount, 0);
    const avgWords = sorted.length > 0 ? Math.round(totalWords / sorted.length) : 0;
    lines.push(`- **Total words:** ${totalWords.toLocaleString()}`);
    lines.push(`- **Average words/entry:** ${avgWords.toLocaleString()}`);
    lines.push(`- **Entries:** ${sorted.length}`);
    lines.push('');

    return lines.join('\n');
}

/**
 * Format a Date to YYYY-MM-DD for export purposes.
 */
function formatDateForExport(date: Date): string {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, '0');
    const d = String(date.getDate()).padStart(2, '0');
    return `${y}-${m}-${d}`;
}
